server:
  port: 8000
spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
routes:
  user-service:
    path: /user-service/**
    serviceId: USER-SERVICE
  product-service:
    path: /product-service/**
    serviceId: product-service

management:
  endpoints:
    web:
      exposure:
        include: routes,filters

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000